image: python

stages:
- test

before_script:
- curl -O https://bootstrap.pypa.io/get-pip.py
- python get-pip.py
- pip install -r requirements.txt

python2:
  image: python:2.7
  stage: test
  script: tox
python37:
  image: python:3.7-rc
  stage: test
  script: tox

