image: python

stages:
    - test
    - deploy

before_script:
    - python -V
    - echo $TWCC_API_KEY, $TWCC_PROJ_CODE
    - curl -O https://bootstrap.pypa.io/get-pip.py
    - python get-pip.py

python27:
  stage: test
  image: python:2.7
  script: 
    - pip install tox
    - tox -e py27
  only:
    - merge_requests

python37:
  stage: test
  image: python:3.7
  script: 
    - pip install tox
    - tox -e py37
  only:
    - merge_requests

manual deploy to PYPI:
  stage: deploy
  variables:
    TWINE_USERNAME: $PYPI_USERNAME
    TWINE_PASSWORD: $PYPI_PASSWORD
  script:
    - pip install twine
    - python setup.py sdist --formats=gztar,zip bdist_wheel
    - twine upload --verbose dist/*
  only:
    - master
    - aug_dev_03
  when: manual
  allow_failure: false


