image: python

stages:
- test
- deploy

before_script:
- curl -O https://bootstrap.pypa.io/get-pip.py
- python get-pip.py
- pip install tox
- echo $TWCC_API_KEY, $TWCC_PROJ_CODE

python27:
  stage: test
  image: python:2.7
  script: tox -e py27
  only: 
  - merge_amber_aug
python37:
  stage: test
  image: python:3.7
  script: tox -e py37

deploy_to_pip:
    stage: deploy
    image: ubuntu:16.04
    scripts:
        whereis git

deploy_to_python:
    stage: deploy
    image: ubuntu:16.04
    scripts:
        whereis git
only:
  - merge_requests
