image: python

stages:
- test

before_script:
- curl -O https://bootstrap.pypa.io/get-pip.py
- python get-pip.py
- pip install tox
- echo $TWCC_API_KEY, $TWCC_PROJ_CODE

python27:
  image: python:2.7
  stage: test
  script: tox -e py27
  only: 
  - merge_amber_aug
python37:
  image: python:3.7
  stage: test
  script: tox -e py37
  only: 
  - merge_amber_aug

