image: python

stages:
    - test
    - deploy

before_script:
    - python -V
    - echo $TWCC_API_KEY, $TWCC_PROJ_CODE
    - curl -O https://bootstrap.pypa.io/get-pip.py
    - python get-pip.py

python27:
  stage: test
  image: python:2.7
  script: 
    - pip install tox
    - tox -e py27
  only:
    - merge_requests

python37:
  stage: test
  image: python:3.7
  script: 
    - pip install tox
    - tox -e py37
  only:
    - merge_requests

python36:
  stage: test
  image: python:3.6
  script: 
    - pip install tox
    - tox -e py36
  only:
    - merge_requests
    - dev
    - master


manual deploy to PYPI:
  stage: deploy
  variables:
    TWINE_USERNAME: $PYPI_USERNAME
    TWINE_PASSWORD: $PYPI_PASSWORD
  script:
    - pip install twine
    - python setup.py sdist bdist_wheel
    - twine upload --verbose dist/*
  only:
    - master
    - dev
  when: manual
  allow_failure: false

manual deploy to GITHUB:
  stage: deploy
  script:
    - git clone https://github.com/TW-NCHC/TWCC-CLI 
    - cd TWCC-CLI/
    - git checkout v0.5
    - git remote add upstream https://git.narl.org.tw/gitlab/twcc/twcc-cli/
    - git fetch upstream
    - git config --global user.email "1803001@narlabs.org.tw"
    - git config --global user.name $GITHUB_USRERNAME
    - git merge upstream/master --no-commit --no-ff --allow-unrelated-histories
    - git commit -m "TWCC-CLI weekly release"
    - git push --set-upstream upstream v0.5
  only:
    - github_cd
    - dev
    - master
  when: manual
  allow_failure: false

