image: python

stages:
    - test

before_script:
    - python -V
    - echo $TWCC_API_KEY, $TWCC_PROJ_CODE
    - curl -O https://bootstrap.pypa.io/get-pip.py
    - python get-pip.py

python27:
  stage: test
  image: python:2.7
  script: 
    - pip install tox
    - tox -e py27

python37:
  stage: test
  image: python:3.7
  script: 
    - pip install tox
    - tox -e py37

