version: 2

jobs:
  # using tox
  toxify:
      docker:
        - image: circleci/python:3.6.6
      environment:
        TOXENV: py27
      steps: &toxsteps
        - checkout
        - run:
            name: Install utils
            command: |
              sudo pip install tox wheel
        - run:
            command: tox

workflows:
  version: 2

  build:
    jobs:
      - toxify
