---
- hosts: twccli
  become: true 
  environment:
    PATH: /home/ubuntu/miniconda3/bin:{{ ansible_env.PATH }}
  tasks:
    - name: Update apt-cache
      apt: update_cache=yes
    - name: Install packages
      apt: pkg={{ item }}
      with_items:
          - wget
          - xz-utils
          - build-essential
          - libsqlite3-dev
          - libreadline-dev
          - libssl-dev
          - openssl
    - name: get miniconda
      become: ubuntu
      get_url: 
        url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
        dest: /tmp/miniconda.sh
    - name: seting miniconda
      become: ubuntu
      shell: bash /tmp/miniconda.sh -b; conda init
    - name: install TWCC-CLI
      become: ubuntu
      shell: pip install TWCC-CLI
    - name: setup twccli
      become: ubuntu
      shell: twccli config init --apikey {{ twcc_api_key }} -pcode {{ twcc_proj_code }} -rc
      args:
        executable: /bin/bash

